### ISSUE TITLE
ERROR Unable to create file /opt/mule/logs/mule-domain-default.log

### ISSUE THREAD

**Issue by racheliurui** [racheliurui/docker-mule-ce-example#2]
```

INFO  2016-08-29 13:28:16,070 [WrapperListener_start_runner] org.mule.module.launcher.coreextension.DefaultMuleCoreExt
ensionManager: Initializing core extensions                                                                           
INFO  2016-08-29 13:28:16,070 [WrapperListener_start_runner] org.mule.module.launcher.coreextension.DefaultMuleCoreExt
ensionManager: Starting core extensions                                                                               
INFO  2016-08-29 13:28:16,082 [WrapperListener_start_runner] org.mule.module.launcher.DefaultArchiveDeployer: ========
========== New Exploded Artifact: default                                                                             
INFO  2016-08-29 13:28:16,091 [WrapperListener_start_runner] org.mule.module.launcher.MuleSharedDomainClassLoader: Usi
ng domain dir /opt/mule/domains/default for domain default                                                            
2016-08-29 13:28:16,170 WrapperListener_start_runner ERROR Unable to create file /opt/mule/logs/mule-domain-default.lo
g java.io.IOException: Permission denied                                                                              
        at java.io.UnixFileSystem.createFileExclusively(Native Method)                                                
        at java.io.File.createNewFile(File.java:1012)                                                                 
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(R
ollingFileManager.java:354)                                                                                           
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(R
ollingFileManager.java:336)                                                                                           
        at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:73)                 
        at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:61)         
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:87
)                                                                                                                     
        at org.apache.logging.log4j.core.appender.RollingFileAppender.createAppender(RollingFileAppender.java:193)    
        at org.mule.module.launcher.log4j2.LoggerContextConfigurer.createRollingFileAppender(LoggerContextConfigurer.j
ava:174)                                                                                                              
```

**Comment by racheliurui** [comment]
Docker is running using ec2-user

```
drwxr-xr-x 2 root root 4096 Aug 29 12:33 mule-app
[ec2-user@ip-172-31-2-77 ~]$ ls -l                                                                                                                                                                                
total 8                                                                                                                                                                                                           
drwxrwxr-x 3 ec2-user ec2-user 4096 Aug 29 12:26 mule
drwxrwxr-x 2 ec2-user ec2-user 4096 Aug 29 13:27 mulelog
[ec2-user@ip-172-31-2-77 ~]$ whoami                                                                                                                                                                               
ec2-user                                                                                                                                                                                                                         
```

**Comment by racheliurui** [comment]
Tried to run docker with sudo and without sudo, the results are the same. 
The volumn being mounted is created by docker and the access is root@root

The issue with this is the folder created by docker service do not have write permission.
after running below cmd to add write access , the issue solved.
chmod 777  /home/ec2-user/data/
